### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by mcardia** [mickeypearce/vscode-oracle-format#13]
When I ask vscode to format the document it asks for the formatter.

In then developer tools I got this error:

```
extensionService.ts:800 Activating extension 'mp.vscode-oracle-format' failed: Cannot read property '0' of undefined.
_logMessageInConsole @ extensionService.ts:800
log.ts:173   ERR An unknown error occurred. Please consult the log for more details.
```

![image](https://user-images.githubusercontent.com/11967511/58580252-0c19e280-8223-11e9-8317-b63e89ae7106.png)

![image](https://user-images.githubusercontent.com/11967511/58580319-32d81900-8223-11e9-9478-b766a4b14086.png)

**Comment by mickeypearce** [comment]
Can you try opening a folder not just a single file?

**Comment by mcardia** [comment]
Opening the folder seens to be working.
Now I think the problema is my style.xml because I get the error: 

Skipped formatting: parse error

But won't work opening just one file?

**Comment by mickeypearce** [comment]
I think there is an error in this line:
https://github.com/mickeypearce/vscode-oracle-format/blob/baac6d9fefeff40976c9f45998b77a0c625e5c61/src/extension.ts#L38
, If you open only a single file. I will fix it.

**Comment by mickeypearce** [comment]
"parse error" should be about your .sql file content. Maybe try first compile it...
