### ISSUE TITLE
input.search is not a function

### ISSUE THREAD

**Issue by bamontelucas** [mickeypearce/vscode-oracle-format#14]
Everytime I try formatting a document vscode shows me the message `input.search is not a function`.

![image](https://user-images.githubusercontent.com/16859135/58644919-aee06880-82d8-11e9-943b-1ef09a7364f7.png)

At the "output" tab there's an `[object Object]` message

![image](https://user-images.githubusercontent.com/16859135/58645002-d46d7200-82d8-11e9-9f00-5f39d80c3d16.png)

Modifying `extensions.js` file I was able to find out the reason and avoid the problem. It appears that the output from the sql call is being returned as an object format instead of a string.

I Made two modifications (modified version at right):
1. 
![image](https://user-images.githubusercontent.com/16859135/58645329-87d66680-82d9-11e9-8072-994f807c4725.png)
2.
![image](https://user-images.githubusercontent.com/16859135/58645409-b2c0ba80-82d9-11e9-90ee-5d4338bbfe36.png)

With these two modifications I am no longer having issues and the output is at least readable

![image](https://user-images.githubusercontent.com/16859135/58645551-f6b3bf80-82d9-11e9-9cc0-f9f5a5f5a7ff.png)

**Comment by mickeypearce** [comment]
@bamontelucas , Thanks for reporting and fixing it. Are you willing to contribute your changes with a PR? If you are up for it, that would be awesome. :)

**Comment by mickeypearce** [comment]
I broke it with the latest change as substitute execPromise:
```
function execPromise(cmd: string): Promise<any> {
  return new Promise(function(resolve, reject) {
    exec(cmd, (error, stdout, stderr) => {
      if (error) {
        reject(error);
      }
      resolve(stdout);
    });
  });
}
```
with
`const execPromise = util.promisify(exec);`

of course `stdout` and `error` are not handlet properly as promise returns an object now.

**Comment by mickeypearce** [comment]
Releasedin v0.1.3. Thanks @bamontelucas .
