### ISSUE TITLE
Skipped formatting: parse error

### ISSUE THREAD

**Issue by lancerXXXX** [mickeypearce/vscode-oracle-format#18]
![image](https://user-images.githubusercontent.com/42160297/76820098-0f7b6a80-6845-11ea-8373-6e303f1e2564.png)

I have add the path of sql.exe

**Comment by mickeypearce** [comment]
It means it is not a valid plsql block. Try with something undisputed like "select 1 from dual;"... :)

**Comment by mickeypearce** [comment]
@lancerXXX , I am closing this issue, ok?

**Comment by lancerXXXX** [comment]
Ok. thank you
