### ISSUE TITLE
Formatter fail

### ISSUE THREAD

**Issue by jianghoy** [mickeypearce/vscode-oracle-format#19]
After using the formatter for a couple of times, it started to return parse error for every SQL script( even those successes before so it cannot be malformed SQL issue). My guess is it might have something to do with oracle sqlcl connection.

Some info that might help:
VS Code version: 1.44.2
Oracle sqlcl version: 19.4.0
OS version: macOS Mojave 10.14.6

**Comment by mickeypearce** [comment]
Can you please post error message from output lane (oracle-format tab)?

**Comment by jianghoy** [comment]
Sure, it's:

> Skipped formatting: parse error

**Comment by mickeypearce** [comment]
Looks like there is something wrong with syntax of file being formated, or not? Can you please try with a simple bullet proof sql like "select 1 from dual;"

**Comment by jianghoy** [comment]
Looks like wrong syntax issue. Simple query works fine.
I just started using formatted so it's always 19.4.
Do you think setting up formatted options would help?

**Comment by mickeypearce** [comment]
No, I don't think it would.. You are trying to format an invalid plsql block. Try to compile it and you will find an error...

**Comment by jianghoy** [comment]
In fact it's not pure plsql per se. It's an in-house ETL platform for more than 10 yrs. At the beginning, it was backed by Oracle DB, later on, the company decided to eat its own dog food so swapped out the backing DB, but the platform remains to use something plsql compatible. At this point, people no longer want to add more features onto it, so there's no formatter available.
