### ISSUE TITLE
settings.json config issue

### ISSUE THREAD

**Issue by fargue** [mickeypearce/vscode-oracle-format#2]
I've added following to my settings.json file:

```
    ......
45    {
46        "oracle-format.sqlcl": "/usr/local/software/sqlcl/bin/sql",
47        "oracle-format.rules": "/usr/local/software/config/sql-formatter.xml"
48    }
```
vscode reports issue with settings.json file:

```
[jsonc] Property expected (45,5)
```

Do I have the entries correct.  Looks like invalid json and I should have something like:

    "propertyname" : {
        "oracle-format.sqlcl": "/usr/local/software/sqlcl/bin/sql",
        "oracle-format.rules": "/Users/jrarnold/config/sql-formatter.xml"
    }

**Comment by mickeypearce** [comment]
Try adding without brackets:
```
......
"oracle-format.sqlcl": "/usr/local/software/sqlcl/bin/sql",
"oracle-format.rules": "/usr/local/software/config/sql-formatter.xml"

```
The {} brackets were meant as top setting brackets.
