### ISSUE TITLE
Error en FORMAT FILE

### ISSUE THREAD

**Issue by JPSantistebanQ** [mickeypearce/vscode-oracle-format#24]
Error en FORMAT FILE c:\...\AppData\Roaming\Code - Insiders\User\workspaceStorage\4331308db0be6e6dda746863ef56745d\mp.vscode-oracle-format\format_temp.sql c:\Users\...\AppData\Roaming\Code - Insiders\User\workspaceStorage\4331308db0be6e6dda746863ef56745d\mp.vscode-oracle-format\format_temp.sql

**Comment by mickeypearce** [comment]
DUP #22
