### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by fernandoch777** [mickeypearce/vscode-oracle-format#25]
Hello, I keep on getting this error and I can't format any SQL files.

Command failed: "sql" /nolog @"c:\Users\fernando\.vscode\extensions\mp.vscode-oracle-format-0.1.5\format.sql" '"sql"' is not recognized as an internal or external command, operable program or batch file.

Any hints for solving this?

Thanks

**Comment by mickeypearce** [comment]
You need sqlcl (sql.exe) to run the extension. Add the path to sql to global paths or use extension settings to set a ful path to sql.exe.
