### ISSUE TITLE
Cannot get to work (parsing error)

### ISSUE THREAD

**Issue by Archinowsk** [mickeypearce/vscode-oracle-format#3]
I'm unable to get this to work. When I hit format, VSCode Developer Tools only prints following and nothing happens:

```
[Extension Host] SQLcl: Release 18.2 Production on Mon Sep 10 17:03:18 2018
Copyright (c) 1982, 2018, Oracle.  All rights reserved.
Formatter rules loaded
```

I tried with the default settings and with the default XML exported from SQL Developer. I'm able to use the formatter with SQLcl.

My specs:

```
SQLcl 18.2
VSCode 1.27.1
NodeJS 8.9.3
Linux 64bit
```

Thanks for a great idea!

**Comment by Archinowsk** [comment]
The same thing with the default formatter.

**Comment by mickeypearce** [comment]
Please try executing from command line (bash?). Unfortunately it wasn't tested on Linux.

``bash
(echo format file ${file} ${file}) | sql /nolog 
``

**Comment by mickeypearce** [comment]
Can you please post console ouput from VSCode Developer Tools when you format document with default formater (without "oracle-format.rules" setting).

**Comment by Archinowsk** [comment]
I was able to get it to work. I'm not sure what happened but now the extension works with default rules and custom rules. Sorry for the trouble and thanks!

Developer Tools prints the same with default and with custom rules:
```
[Extension Host] SQLcl: Release 18.2 Production on Wed Sep 12 12:39:44 2018
Copyright (c) 1982, 2018, Oracle.  All rights reserved.
Formatter rules loaded
```

**Comment by mickeypearce** [comment]
I could search output for parsing error and raise the error to UI.

Sqlcl Output:
`Skipped formatting ...\format_temp.sql -- parse error`
