### ISSUE TITLE
Format unsaved documents

### ISSUE THREAD

**Issue by stuartisaac** [mickeypearce/vscode-oracle-format#4]
I request that the extension be made to work for unsaved documents. This could presumably be implemented by detecting if there are unsaved changes, and if so, copying the contents to a temporary file, having SQLcl do its thing on the temp file, then copying the formatted contents back to the document.

**Comment by mickeypearce** [comment]
#1

**Comment by stuartisaac** [comment]
Yes, that looks great. Thanks!
