### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by juanitolaguna** [mickeypearce/vscode-oracle-format#7]
Command failed: "sql" /nolog @c:\Users\user.DLInternal\AppData\Roaming\Code\User\workspaceStorage\c3e16703c375dd2409f4f36c6fcfcd3c\mp.vscode-oracle-format\format.sql
Der Befehl ""sql"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

**Comment by mickeypearce** [comment]
Install "Oracle SQLcl" (sql.exe) and add it to your "PATH". 

Or add to `setting.json` absolute path to sql:
`"oracle-format.sqlcl": "/absolute/path/to/sql.exe"`

**Comment by mickeypearce** [comment]
Take a lot at #1.
