### ISSUE TITLE
Format On Save doesn't appear to work

### ISSUE THREAD

**Issue by zhudock** [mickeypearce/vscode-oracle-format#8]
I do see the command execute, the active editor script is copied to a temp file, that temp file gets formatted, but the contents never get put back in the editor.

I'm using the latest VSCode and latest version of this extension on Windows 10 Pro.

**Comment by mickeypearce** [comment]
Hey @zhudock ,
have you tried increasing default timeout: `"editor.formatOnSaveTimeout": 10000` as formatting takes quite some time for larger files.

**Comment by zhudock** [comment]
it seems 10000 isn't sufficient. bumped it up to 15000 and things seem OK. Sorry for the false positive.

**Comment by mickeypearce** [comment]
I updated the readme to make it more clear.
